#pragma once

#define WINDOW_W 800
#define WINDOW_H 600

#define CENTER(SCOPE_SIZE, OBJECT_SIZE) (SCOPE_SIZE - OBJECT_SIZE)/2

#define KB_BUTTON_SIZE 60
#define KB_SPACE_BETWEEN_KEYS 12
#define KB_WIDTH (10 * KB_BUTTON_SIZE + 9 * KB_SPACE_BETWEEN_KEYS)
#define KB1_LEFT_MARGIN CENTER(WINDOW_W, KB_WIDTH)
#define KB2_LEFT_MARGIN KB1_LEFT_MARGIN + KB_BUTTON_SIZE/3
#define KB3_LEFT_MARGIN KB2_LEFT_MARGIN + 2*KB_BUTTON_SIZE/3
#define KB_VERTICAL_START 366
#define HANGMAN_BASE_POS_X 650
#define HANGMAN_BASE_POS_Y 250